import { SidebarNavItem } from '@shell/models/sidebar-nav-item.model';

export const DEFAULT_SIDEBAR_NAV_ITEMS: readonly SidebarNavItem[] = [
  {
    id: 'sales',
    label: 'Menú',
    icon: 'house',
    route: '/sales',
    exact: true,
    roles: ['admin', 'seller', 'manager'],
  },
  {
    id: 'inventory',
    label: 'Inventario',
    icon: 'package',
    route: '/inventory',
    roles: ['admin', 'seller', 'manager'],
  },
  {
    id: 'reports',
    label: 'Reportes',
    icon: 'bar-chart-3',
    route: '/reports',
    roles: ['admin', 'manager', 'seller'],
  },
  {
    id: 'history',
    label: 'Historial',
    icon: 'history',
    route: '/history',
    roles: ['admin', 'manager', 'seller'],
  },
  {
    id: 'suppliers',
    label: 'Proveedores',
    icon: 'truck',
    route: '/suppliers',
    roles: ['admin', 'manager', 'seller'],
  },
  {
    id: 'branches',
    label: 'Sucursales',
    icon: 'building',
    route: '/branches',
    roles: ['admin'],
  },
  {
    id: 'branch-pricing',
    label: 'Precios por Sucursal',
    icon: 'tag',
    route: '/branch-pricing',
    roles: ['admin'],
  },
  {
    id: 'clients',
    label: 'Clientes',
    icon: 'users',
    route: '/clients',
    roles: ['admin', 'manager', 'seller'],
  },
  {
    id: 'inventory-by-branch',
    label: 'Inventario Sucursal',
    icon: 'warehouse',
    route: '/inventory-by-branch',
    roles: ['admin', 'manager'],
  },
  {
    id: 'admin',
    label: 'Administración',
    icon: 'settings',
    route: '/admin',
    roles: ['admin', 'seller', 'manager'],
  },
  {
    id: 'notifications',
    label: 'Notificaciones',
    icon: 'bell',
    route: '/notifications',
    roles: ['admin', 'seller', 'manager'],
  },
  {
    id: 'manager-cashiers',
    label: 'Cajeros',
    icon: 'users',
    route: '/manager/cashiers',
    roles: ['admin', 'seller', 'manager'],
  },
];
