export const AppRoutes = {
  app: 'app',
  login: 'login',
  sales: 'sales',
  inventory: 'inventory',
  reports: 'reports',
  history: 'history',
  suppliers: 'suppliers',
  branches: 'branches',
  clients: 'clients',
  admin: 'admin',
  manager: 'manager',
  notifications: 'notifications',
  inventoryByBranch: 'inventory-by-branch',
  branchPricing: 'branch-pricing',
} as const;
